# Site settings
title:          Enthusiast
description:    "Just another undergrad trying to be a Geek"
baseurl:        "/"
url:            "https://viggi-v.github.io"

# Author
author:
  name:         Vighnesh Velayudhan
  email:        vighneshvelayudhan@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
